# Generated by Django 3.2.3 on 2021-05-18 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('receipt', models.ImageField(null=True, upload_to='receipts/%Y-%m-%d/assets/')),
                ('document', models.FileField(null=True, upload_to='documents/%Y-%m-%d/assets/')),
                ('date_made', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-date_made'],
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('cleared', models.BooleanField(default=False)),
                ('date_made', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Debtor',
                'verbose_name_plural': 'Dbtors',
                'ordering': ['-date_made'],
            },
        ),
    ]
