# Generated by Django 3.2.3 on 2021-05-18 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('receipt', models.ImageField(null=True, upload_to='receipts/%Y-%m-%d/purchases/')),
                ('document', models.FileField(null=True, upload_to='documents/%Y-%m-%d/purchases/')),
                ('date_made', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-date_made'],
            },
        ),
        migrations.CreateModel(
            name='PurchasesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('receipt', models.ImageField(null=True, upload_to='receipts/%Y-%m-%d/purchases/returns/')),
                ('document', models.FileField(null=True, upload_to='documents/%Y-%m-%d/purchases/returns/')),
                ('amount', models.IntegerField(default=0)),
                ('date_made', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'Purchases Return',
                'verbose_name_plural': 'Purchases Returns',
                'ordering': ['-date_made'],
            },
        ),
    ]
